### ISSUE TITLE
Files Not Found

### ISSUE THREAD

**Issue by JimLynchCodes** [HistoireDeBabar/generator-universal-react-and-redux#2]
Hi. I cloned this and tried to run `npm run dev`, but I cam getting these errros that files are not found. What can I do to fix this? Thanks.

![redux_universal_example](https://cloud.githubusercontent.com/assets/5354163/18028556/04fdbcb0-6c50-11e6-8904-170e10f23105.png)

**Comment by HistoireDeBabar** [comment]
Hey,

What you want to do is use http://localhost.com:8080 :- which is the dev server.  The dev server proxies through 3000 (hence why it's running).  However webpack dev mode bundles everything in memory (thus the files being missing).  If you go to 8080 however you'll be on the dev server and will avoid this issue.
I've put a section in the readme trying to explain this a little more clearly.  Hope that helps.
